apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: footfalls-ingress
  namespace: footfalls-production
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - api.footfalls.app
      secretName: footfalls-tls-secret
  rules:
    - host: api.footfalls.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: footfalls-backend-svc
                port:
                  number: 80
