// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2dRkrhpPrkNA61yD2vD6FxoE4ZgOBiR4',
    appId: '1:405698170811:android:6dc447c718b423d5ba3e9e',
    messagingSenderId: '405698170811',
    projectId: 'footfalls-6dab0',
    storageBucket: 'footfalls-6dab0.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN8y_psUK2GjrrDZPAEbDxen46jOvEGuk',
    appId: '1:405698170811:web:8bfe3302c3d8e58aba3e9e',
    messagingSenderId: '405698170811',
    projectId: 'footfalls-6dab0',
    authDomain: 'footfalls-6dab0.firebaseapp.com',
    storageBucket: 'footfalls-6dab0.firebasestorage.app',
    measurementId: 'G-SLS8PFD7TZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA08Js41v0gmVXiTRXlLSxgq_J9InZbO5Q',
    appId: '1:405698170811:ios:75a7ddd61ae5f252ba3e9e',
    messagingSenderId: '405698170811',
    projectId: 'footfalls-6dab0',
    storageBucket: 'footfalls-6dab0.firebasestorage.app',
    iosClientId: '405698170811-4asl07un8p9ibg8qb77e5hdu0h3ll283.apps.googleusercontent.com',
    iosBundleId: 'com.example.footfallsApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA08Js41v0gmVXiTRXlLSxgq_J9InZbO5Q',
    appId: '1:405698170811:ios:75a7ddd61ae5f252ba3e9e',
    messagingSenderId: '405698170811',
    projectId: 'footfalls-6dab0',
    storageBucket: 'footfalls-6dab0.firebasestorage.app',
    iosClientId: '405698170811-4asl07un8p9ibg8qb77e5hdu0h3ll283.apps.googleusercontent.com',
    iosBundleId: 'com.example.footfallsApp',
  );
}
