name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: 🚀 FootFalls Analytics ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          files: app-release.apk
          fail_on_unmatched_files: false
